name: teatally
channels:
  - defaults
  - conda-forge
dependencies:
  - numpy=1.21.2
  - pandas=1.3.3
  - pip=23.2.1
  - python=3.8.18
  - seaborn=0.11.2
  - streamlit=1.31.1
  - pip:
      - firebase-admin==6.4.0
